# Setup
title: 韩涛 (Han Tao)
description: 多学多问，多做多担当
url: https://ht894419944.github.io
avatar: /hantao.jpg
paginate: 5
permalink: pretty
cover_image: /anechoic.png

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
# twitter:
#   username: vszhub
#   card: summary
# logo: logo.png
social:
  name: Han Tao
  links:
    # - https://twitter.com/vszhub
    - https://github.com/ht894419944
google_site_verification: xxxxx
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: Han Tao
  url: https://github.com/ht894419944/
  email: than@idt.eitech.edu.cn
